controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if(Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        } else{
            if (Yii::$app->user->can('admin-empresa')) {
                return $this->redirect('centro/indexempresa');
            }
            return $this->render('index');
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionLanguage(){
        $language = Yii::$app->request->post('language');

        Yii::$app->language = $language;

        $languageCookie = new \yii\web\Cookie([
            'name' => 'language',
            'value' => $language,
            'expire' => time() + 60 * 60 * 24 * 30, //30 dias
        ]);                
        Yii::$app->response->cookies->add($languageCookie);

        return $this->goBack();
    } 
}

views/theme/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<!-- Main content -->
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href='<?= Yii::$app->homeUrl ?>'>return to dashboard</a> or try using the search
                form.
            </p>

            <form class='search-form'>
                <div class='input-group'>
                    <input type="text" name="search" class='form-control' placeholder="Search"/>

                    <div class="input-group-btn">
                        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

views/theme/site/login.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use kartik\select2\Select2;
use dmstr\widgets\Alert;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->registerCssFile(Yii::$app->request->baseUrl . '/css/site.css');
$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="row login-contenedor">
    
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 img-contenedor">
        <img src="<?= Yii::$app->request->baseUrl ?>/img/banner-second.jpg" class="fondo-img" width="100%"/>
    </div>

    <div class="col-xs-12 col-sm-12  col-md-4  col-lg-4 form-contenedor">
        <div class="login-box-body">
            <div class="row">
                <div class="col-xs-12">
                    <?= Alert::widget() ?>
                </div>
            </div>
            <div class="login-logo">
                <a href="#">
                    <span class="logo-lg"><img src="<?= Yii::$app->request->baseUrl ?>/img/lux_logo.png" height="40" style="margin-top:-5px;"/><?= Yii::$app->name ?></span>
                </a>
            </div>
            
            <p class="login-box-msg text-left"><?= Yii::t('app', $this->title); ?></p>
            <br>
            <br>
            <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>
            <div class="row">
                <div class="col-xs-12">
                    <?= $form
                        ->field($model, 'username', $fieldOptions1)
                        ->label(false)
                        ->textInput(['placeholder' => Yii::t('app', 'Username')]) ?>
                </div>
                <div class="col-xs-12">
                    <?= $form
                        ->field($model, 'password', $fieldOptions2)
                        ->label(false)
                        ->passwordInput(['placeholder' => Yii::t('app', 'Password')]) ?>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-xs-7">
                    <?= $form->field($model, 'rememberMe')->label(Yii::t('app', "Remember me"))->checkbox() ?>
                </div>
                <!-- /.col -->
                <div class="col-xs-5">
                    <?= Html::submitButton(Yii::t('app', $this->title), ['class' => 'btn btn-red btn-block btn-flat', 'name' => 'login-button']) ?>
                </div>
                <!-- /.col -->
            </div>
            <?php ActiveForm::end(); ?>
            <?php echo Html::a(Yii::t('app', "Forgot your password?"), Url::to(['admin/user/request-password-reset'])) ?>
            <!-- /.lenguage -->
            <br><br>
            <div class="row">
                <div class="col-xs-12 col-md-offset-6 col-md-4 pull-right">
                    
                    <?= Select2::widget([
                            'name' => 'language',
                            'attribute' => 'language',
                            'id' => 'lang',
                            'hideSearch' => true,
                            'pluginEvents' => [
                                "change" => "function() {
                                                var data = new Array();    
                                                data.push({name: 'language', value: $(this).val()});
                                                $.ajax({
                                                    type: 'POST',
                                                    data: data,
                                                    url: '".Url::toRoute(['site/language'])."',
                                                    success: function () {
                                                    }
                                                });
                                            }",
                            ],
                            'data' => ['en' => 'English', 'es' => 'Español',],
                            'value' => Yii::$app->language,
                        ]);
                    ?>
                </div>
            </div><!-- /.lenguage -->
        </div> <!-- /.login-box-body -->

    </div> <!-- /.login-box -->
</div>